---
- name: Include default vars
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"

- name: Create a VM
  ansible.builtin.include_role:
    name: iac-terraform-runner
  vars:
    state: present
    terraform_variables:
      vm: "{{ resource }}"
      host: "{{ host }}"