---
- name: Include default vars
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"

- debug: 
    var: provider

- name: Create a VM
  ansible.builtin.include_role:
    name: iac-terraform-runner
  vars:
    provider: "{{ project }}"
    state: apply
    variables:
      terraform_variables:
        vm: "{{ resource }}"
        host: "{{ host }}"